const {
  login,
  logout,
  verifyUser,
  changePassword,
  sendPinCode,
  addRole,
  addDepartment,
  addDesignation,
  addUser,
  getAllUsers,
  verifyPincode,
  resetPassword,
  updateUser,
  searchUser,
  getUser,
  allocateLeaves,
  applyLeave,
  getLeaves,
  getLeaveBalance,
  changeLeaveSatus,
  CancelLeaveRequest,
  getLeaveBalanceOfUsers,
  getLeaveRequestOfUsers,
  getUpcomingBirthdays,
  getUpcomingAnniversy,
  getOrganizationData,
  getAttendance,
  getAllAttendance,
  getLeaveByDate,
  getUserLeaveByDate,
  editLeave
} = require("./userController");

const {
  addPersonalDetails,
  updatePersonalDetails,
  updateFamilyDetails,
  updateQualificationDetails,
  updateExperienceDetails,
  getEmployeeDetails,
  getEmployeePersonalDetails,
  uploadProfile,
  getAllEmployees,
} = require("./employeeController");

const {
  addPermission,
  adminAddDepartment,
  adminAddRole,
  adminAddDesignation,
  addAdmin,
  addLeaveType,
  getDepartments,
  getDesignations,
  getRoles,
  getLeavesType,
  attendance,
  updateThought,
  updatePoshPolicy,
  updateHolidayCalendar,
  updateNotice,
  updatePolicy
} = require("./adminController");

module.exports = {
  //user
  login,
  logout,
  verifyUser,
  changePassword,
  sendPinCode,
  addRole,
  addDepartment,
  addDesignation,
  addUser,
  getAllUsers,
  verifyPincode,
  resetPassword,
  updateUser,
  searchUser,
  getUser,
  allocateLeaves,
  applyLeave,
  editLeave,
  getLeaves,
  getLeaveBalance,
  changeLeaveSatus,
  CancelLeaveRequest,
  getLeaveBalanceOfUsers,
  getLeaveRequestOfUsers,
  getUpcomingBirthdays,
  getUpcomingAnniversy,
  getOrganizationData,
  getAttendance,
  getAllAttendance,
  getLeaveByDate,
  getUserLeaveByDate,

  //employee
  addPersonalDetails,
  updatePersonalDetails,
  updateFamilyDetails,
  updateQualificationDetails,
  updateExperienceDetails,
  getEmployeeDetails,
  getEmployeePersonalDetails,
  uploadProfile,
  getAllEmployees,

  //admin
  addAdmin,
  addPermission,
  adminAddDepartment,
  adminAddRole,
  adminAddDesignation,
  addLeaveType,
  getDepartments,
  getDesignations,
  getRoles,
  getLeavesType,
  attendance,
  updateThought,
  updatePoshPolicy,
  updateHolidayCalendar,
  updateNotice,
  updatePolicy

};
